# Generated by Django 3.2.11 on 2022-01-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220110_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
