# Generated by Django 3.2.11 on 2022-01-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='iv',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
