# Generated by Django 3.2.11 on 2022-01-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_myuser_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='password_db',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
